# Generic
VONAGE_API_KEY: The API key of the account.
VONAGE_API_SECRET: The API secret of the account.
ACCOUNT_ID: The account ID to target

# Account API
VONAGE_SECRET_ID.DELETE: The ID of the secret to delete.
VONAGE_SECRET_ID.FETCH: The ID of the secret to retrieve.
SMS_CALLBACK_URL: The publicly-accessible URL that Vonage should send information to when your Vonage number receives an SMS
NEW_SECRET: The new API secret for the API key.
